import 'package:flutter/material.dart';

import 'TranslationService.dart';

class IconsMap {
  Map<Translation, IconData> allIcons = {

    //a

    Translation("list"): Icons.list,
    Translation("infinity"): Icons.all_inclusive,
    Translation("accessibility"): Icons.accessibility,
    Translation("favorite"): Icons.favorite,
    Translation("snow_flake"): Icons.ac_unit,
    Translation("alarm"): Icons.access_alarm,
    Translation("time"): Icons.access_time,
    Translation("handicap"): Icons.accessible,
    Translation("handicap_forward"): Icons.accessible_forward_outlined,
    Translation("account_balance"): Icons.account_balance,
    Translation("wallet"): Icons.account_balance_wallet,
    Translation("account_box"): Icons.account_box,
    Translation("account_circle"): Icons.account_circle,
    Translation("hierarchy"): Icons.account_tree,
    Translation("hierarchy_empty"): Icons.account_tree_outlined,
    Translation("ad_units"): Icons.ad_units,
    Translation("adb"): Icons.adb,
    Translation("add"): Icons.add,
    Translation("add_a_photo"): Icons.add_a_photo,
    Translation("add_alarm"): Icons.add_alarm,
    Translation("add_alert"): Icons.add_alert,
    Translation("add_box"): Icons.add_box,
    Translation("add_business"): Icons.add_business,
    Translation("add_call"): Icons.add_call,
    Translation("add_chart"): Icons.add_chart,
    Translation("add_circle"): Icons.add_circle,
    Translation("add_comment"): Icons.add_comment,
    Translation("add_link"): Icons.add_link,
    Translation("add_location"): Icons.add_location_alt_outlined,
    Translation("add_add_moderator"): Icons.add_moderator,
    Translation("add_image"): Icons.add_photo_alternate_outlined,
    Translation("add_reaction"): Icons.add_reaction,
    Translation("add_road"): Icons.add_road,
    Translation("add_shopping_cart"): Icons.add_shopping_cart,
    Translation("add_task"): Icons.add_task,
    Translation("add_to_drive"): Icons.add_to_drive,
    Translation("add_to_home_screen"): Icons.add_to_home_screen,
    Translation("add_to_photos_outlined"): Icons.add_to_photos_outlined,
    Translation("add_to_queue"): Icons.add_to_queue,
    Translation("adjust") : Icons.adjust,
    Translation("admin_panel_settings") : Icons.admin_panel_settings,
    Translation("agriculture") : Icons.agriculture,
    Translation("air") : Icons.air,
    Translation("airline_seat_flat") : Icons.airline_seat_flat,
    Translation("airline_seat_flat_angled") : Icons.airline_seat_flat_angled,
    Translation("airline_seat_individual_suite") : Icons.airline_seat_individual_suite,
    Translation("airline_seat_legroom_extra") : Icons.airline_seat_legroom_extra,
    Translation("airline_seat_legroom_normal") : Icons.airline_seat_legroom_normal,
    Translation("airline_seat_legroom_reduced") : Icons.airline_seat_legroom_reduced,
    Translation("airline_seat_recline_extra") : Icons.airline_seat_recline_extra,
    Translation("airline_seat_recline_normal") : Icons.airline_seat_recline_normal,
    Translation("airplane_ticket") : Icons.airplane_ticket,
    Translation("airplanemode_active") : Icons.airplanemode_active,
    Translation("airplanemode_inactive") : Icons.airplanemode_inactive,
    Translation("airplay") : Icons.airplay,
    Translation("airport_shuttle") : Icons.airport_shuttle,
    Translation("alarm_off") : Icons.alarm_off,
    Translation("alarm_on") : Icons.alarm_on,
    Translation("album") : Icons.album,
    Translation("align_horizontal_center") : Icons.align_horizontal_center,
    Translation("align_horizontal_left") : Icons.align_horizontal_left,
    Translation("align_horizontal_right") : Icons.align_horizontal_right,
    Translation("align_vertical_center") : Icons.align_vertical_center,
    Translation("align_vertical_bottom") : Icons.align_vertical_bottom,
    Translation("align_vertical_top") : Icons.align_vertical_top,
    Translation("all_inbox") : Icons.all_inbox,
    Translation("all_out") : Icons.all_out,
    Translation("alt_route") : Icons.alt_route,
    Translation("alternate_email") : Icons.alternate_email,
    Translation("amp_stories") : Icons.amp_stories,
    Translation("analytics") : Icons.analytics,
    Translation("anchor") : Icons.anchor,
    Translation("android") : Icons.android,
    Translation("animation") : Icons.animation,
    Translation("announcement") : Icons.announcement,
    Translation("aod") : Icons.aod,
    Translation("apartment") : Icons.apartment,
    Translation("api") : Icons.api,
    Translation("app_blocking"): Icons.app_blocking,
    Translation("app_registration") : Icons.app_registration,
    Translation("app_settings_alt") : Icons.app_settings_alt,
    Translation("approval") : Icons.approval,
    Translation("apps") : Icons.apps,
    Translation("architecture") : Icons.architecture,
    Translation("archive") : Icons.archive,
    Translation("arrow_back") : Icons.arrow_back,
    Translation("arrow_downward") : Icons.arrow_downward,
    Translation("arrow_forward") : Icons.arrow_forward,
    Translation("arrow_upward") : Icons.arrow_upward,
    Translation("art_track") : Icons.art_track,
    Translation("article") : Icons.article,
    Translation("aspect_ratio") : Icons.aspect_ratio,
    Translation("assessment") : Icons.assessment,
    Translation("assignment") : Icons.assignment,
    Translation("assignment_late") : Icons.assignment_late,
    Translation("assignment_return") : Icons.assignment_return,
    Translation("assignment_returned") : Icons.assignment_returned,
    Translation("assignment_turned_in") : Icons.assignment_turned_in,
    Translation("assistant") : Icons.assistant,
    Translation("assistant_direction") : Icons.assistant_direction,
    Translation("assistant_navigation") : Icons.assistant_navigation,
    Translation("assistant_photo") : Icons.assistant_photo,
    Translation("atm") : Icons.atm,
    Translation("attach_email") : Icons.attach_email,
    Translation("attach_file") : Icons.attach_file,
    Translation("attach_money") : Icons.attach_money,

    //b
    // "baby_changing_station" : Icons.baby_changing_station,
    // "backpack2" : Icons.backpack,
    // "backspace" : Icons.backspace,
    // "backup" : Icons.backup,
    // "badge" : Icons.badge,
    // "bakery_dining" : Icons.bakery_dining,
    // "balcony" : Icons.balcony,
    // "ballot" : Icons.ballot,
    // "bar_chart" : Icons.bar_chart,
    // "batch_prediction" : Icons.batch_prediction,
    // "bathroom" : Icons.bathroom,
    // "bathtub" : Icons.bathtub,
    // "battery_alert" : Icons.battery_alert,
    // "battery_charging_full" : Icons.battery_charging_full,
    // "battery_full" : Icons.battery_full,
    // "battery_unknown" : Icons.battery_unknown,
    // "beach_access" : Icons.beach_access,
    // "bed" : Icons.bed,
    // "bedroom_baby" : Icons.bedroom_baby,
    // "bedroom_child" : Icons.bedroom_child,
    // "bedroom_parent" : Icons.bedroom_parent,
    // "bedtime" : Icons.bedtime,
    // "beenhere" : Icons.beenhere,
    // "bento" : Icons.bento,
    // "bike_scooter" : Icons.bike_scooter,
    // "biotech" : Icons.biotech,
    // "blender" : Icons.blender,
    // "block" : Icons.block,
    // "bloodtype" : Icons.bloodtype,
    // "bluetooth" : Icons.bluetooth,
    // "bluetooth_connected" : Icons.bluetooth_connected,
    // "bluetooth_disabled" : Icons.bluetooth_disabled,
    // "blur_circular" : Icons.blur_circular,
    // "blur_linear" : Icons.blur_linear,
    // "blur_off" : Icons.blur_off,
    // "blur_on" : Icons.blur_on,
    // "bolt" : Icons.bolt,
    // "book" : Icons.book,
    // "book_online" : Icons.book_online,
    // "bookmark" : Icons.bookmark,
    // "bookmark_remove" : Icons.bookmark_remove,
    // "border_color" : Icons.border_color,
    // "border_all" : Icons.border_all,
    // "border_clear" : Icons.border_clear,
    // "branding_watermark" : Icons.branding_watermark,
    // "breakfast_dining" : Icons.breakfast_dining,
    // "brunch_dining" : Icons.brunch_dining,
    // "brush" : Icons.brush,
    // "bubble_chart" : Icons.bubble_chart,
    // "bug_report" : Icons.bug_report,
    // "build" : Icons.build,
    // "bungalow" : Icons.bungalow,
    // "burst_mode" : Icons.burst_mode,
    // "bus_alert" : Icons.bus_alert,
    // "business" : Icons.business,
    //
    //
    // //c
    // "calendar_view_week" : Icons.calendar_view_week,
    // "calendar_view_month" : Icons.calendar_view_month,
    // "calendar_view_day" : Icons.calendar_view_day,
    // "clear" : Icons.clear,
    // "cabin" : Icons.cabin,
    // "cached" : Icons.cached,
    // "cake" : Icons.cake,
    // "calculate" : Icons.calculate,
    // "calendar_today" : Icons.calendar_today,
    // "call" : Icons.call,
    // "call_end" : Icons.call_end,
    // "call_made" : Icons.call_made,
    // "call_merge" : Icons.call_merge,
    // "call_missed" : Icons.call_missed,
    // "call_received" : Icons.call_received,
    // "camera" : Icons.camera,
    // "camera_front" : Icons.camera_front,
    // "camera_rear" : Icons.camera_rear,
    // "camera_roll" : Icons.camera_roll,
    // "campaign" : Icons.campaign,
    // "cancel" : Icons.cancel,
    // "cancel_schedule_send" : Icons.cancel_schedule_send,
    // "car_rental" : Icons.car_rental,
    // "car_repair" : Icons.car_repair,
    // "card_membership" : Icons.card_membership,
    // "carpenter" : Icons.carpenter,
    // "cases" : Icons.cases,
    // "casino" : Icons.casino,
    // "cast" : Icons.cast,
    // "category" : Icons.category,
    // "compare_arrows" : Icons.compare_arrows,
    // "celebration" : Icons.celebration,
    // "chair" : Icons.chair,
    // "chalet" : Icons.chalet,
    // "change_history" : Icons.change_history,
    // "charging_station" : Icons.charging_station,
    // "checklist" : Icons.checklist,
    // "checkroom" : Icons.checkroom,
    // "child_care" : Icons.child_care,
    // "child_friendly" : Icons.child_friendly,
    // "clean_hands" : Icons.clean_hands,
    // "circle" : Icons.circle,
    // "cleaning_services" : Icons.cleaning_services,
    // "close" : Icons.close,
    // "close_fullscreen" : Icons.close_fullscreen,
    // "closed_caption" : Icons.closed_caption,
    // "closed_caption_disabled" : Icons.closed_caption_disabled,
    // "closed_caption_off" : Icons.closed_caption_off,
    // "cloud" : Icons.cloud,
    // "cloud_done" : Icons.cloud_done,
    // "cloud_download" : Icons.cloud_download,
    // "cloud_off" : Icons.cloud_off,
    // "code" : Icons.code,
    // "coffee" : Icons.coffee,
    // "coffee_maker" : Icons.coffee_maker,
    // "collections" : Icons.collections,
    // "color_lens" : Icons.color_lens,
    // "colorize" : Icons.colorize,
    // "comment" : Icons.comment,
    // "commute" : Icons.commute,
    // "compass_calibration" : Icons.compass_calibration,
    // "compress" : Icons.compress,
    // "computer" : Icons.computer,
    // "connect_without_contact" : Icons.connect_without_contact,
    // "connected_tv" : Icons.connected_tv,
    // "construction" : Icons.construction,
    // "contact_mail" : Icons.contact_mail,
    // "contact_support" : Icons.contact_support,
    // "contactless" : Icons.contactless,
    // "contacts" : Icons.contacts,
    // "content_copy" : Icons.content_copy,
    // "content_cut" : Icons.content_cut,
    // "content_paste" : Icons.content_paste,
    //
    //
    //
    // //d
    //
    // "delete" : Icons.delete,
    // "dangerous" : Icons.dangerous,
    // "dark_mode" : Icons.dark_mode,
    // "dashboard" : Icons.dashboard,
    // "dashboard_customize" : Icons.dashboard_customize,
    // "data_saver_off" : Icons.data_saver_off,
    // "data_saver_on" : Icons.data_saver_on,
    // "data_usage" : Icons.data_usage,
    // "date_range" : Icons.date_range,
    // "deck" : Icons.deck,
    // "dehaze" : Icons.dehaze,
    // "delivery_dining" : Icons.delivery_dining,
    // "departure_board" : Icons.departure_board,
    // "description" : Icons.description,
    // "design_services" : Icons.design_services,
    // "desktop_access_disabled" : Icons.desktop_access_disabled,
    // "desktop_mac" : Icons.desktop_mac,
    // "details" : Icons.details,
    // "developer_board" : Icons.developer_board,
    // "developer_board_off" : Icons.developer_board_off,
    // "developer_mode" : Icons.developer_mode,
    // "device_hub" : Icons.device_hub,
    // "device_thermostat" : Icons.device_thermostat,
    // "device_unknown" : Icons.device_unknown,
    // "devices" : Icons.devices,
    // "dialer_sip" : Icons.dialer_sip,
    // "dialpad" : Icons.dialpad,
    // "dining" : Icons.dining,
    // "dinner_dining" : Icons.dinner_dining,
    // "directions" : Icons.directions,
    // "directions_bike" : Icons.directions_bike,
    // "directions_boat" : Icons.directions_boat,
    // "directions_bus" : Icons.directions_bus,
    // "directions_car" : Icons.directions_car,
    // "directions_ferry" : Icons.directions_ferry,
    // "directions_off" : Icons.directions_off,
    // "directions_run" : Icons.directions_run,
    // "directions_subway" : Icons.directions_subway,
    // "directions_train" : Icons.directions_train,
    // "directions_walk" : Icons.directions_walk,
    // "dirty_lens" : Icons.dirty_lens,
    // "disabled_by_default" : Icons.disabled_by_default,
    // "disc_full" : Icons.disc_full,
    // "dns" : Icons.dns,
    // "do_disturb" : Icons.do_disturb,
    // "do_disturb_off" : Icons.do_disturb_off,
    // "do_not_step" : Icons.do_not_step,
    // "do_not_touch" : Icons.do_not_touch,
    // "dock" : Icons.dock,
    // "document_scanner" : Icons.document_scanner,
    // "domain" : Icons.domain,
    // "done" : Icons.done,
    // "done_all" : Icons.done_all,
    // "donut_large" : Icons.donut_large,
    // "door_back" : Icons.door_back,
    // "door_front" : Icons.door_front,
    // "door_sliding" : Icons.door_sliding,
    // "doorbell" : Icons.doorbell,
    // "downhill_skiing" : Icons.downhill_skiing,
    // "download" : Icons.download,
    // "download_done" : Icons.download_done,
    // "downloading" : Icons.downloading,
    // "drafts" : Icons.drafts,
    // "drive_file_move" : Icons.drive_file_move,
    // "dry" : Icons.dry,
    // "dry_cleaning" : Icons.dry_cleaning,
    // "duo" : Icons.duo,
    // "dvr" : Icons.dvr,
    //
    //
    //
    // //e
    //
    // "e_mobiledata" : Icons.e_mobiledata,
    // "earbuds" : Icons.earbuds,
    // "eco" : Icons.eco,
    // "edgesensor_high" : Icons.edgesensor_high,
    // "edgesensor_low" : Icons.edgesensor_low,
    // "edit" : Icons.edit,
    // "edit_attributes" : Icons.edit_attributes,
    // "edit_location" : Icons.edit_location,
    // "edit_notifications" : Icons.edit_notifications,
    // "edit_off" : Icons.edit_off,
    // "edit_road" : Icons.edit_road,
    // "eight_mp" : Icons.eight_mp,
    // "eighteen_mp" : Icons.eighteen_mp,
    // "eject" : Icons.eject,
    // "elderly" : Icons.elderly,
    // "electric_bike" : Icons.electric_bike,
    // "electric_car" : Icons.electric_car,
    // "electric_moped" : Icons.electric_moped,
    // "electric_rickshaw" : Icons.electric_rickshaw,
    // "electric_scooter" : Icons.electric_scooter,
    // "electrical_services" : Icons.electrical_services,
    // "elevator" : Icons.elevator,
    // "eleven_mp" : Icons.eleven_mp,
    // "email" : Icons.email,
    // "emoji_emotions" : Icons.emoji_emotions,
    // "emoji_events" : Icons.emoji_events,
    // "emoji_flags" : Icons.emoji_flags,
    // "emoji_food_beverage" : Icons.emoji_food_beverage,
    // "emoji_nature" : Icons.emoji_nature,
    // "emoji_objects" : Icons.emoji_objects,
    // "emoji_people" : Icons.emoji_people,
    // "emoji_symbols" : Icons.emoji_symbols,
    // "emoji_transportation" : Icons.emoji_transportation,
    // "engineering" : Icons.engineering,
    // "equalizer" : Icons.equalizer,
    // "error" : Icons.error,
    // "escalator" : Icons.escalator,
    // "escalator_warning" : Icons.escalator_warning,
    // "euro" : Icons.euro,
    // "ev_station" : Icons.ev_station,
    // "event_available" : Icons.event_available,
    // "event_busy" : Icons.event_busy,
    // "event_seat" : Icons.event_seat,
    // "exit_to_app" : Icons.exit_to_app,
    // "expand" : Icons.expand,
    // "explicit" : Icons.explicit,
    // "explore" : Icons.explore,
    // "explore_off" : Icons.explore_off,
    // "exposure" : Icons.exposure,
    // "extension" : Icons.extension,
    //
    //
    // // f
    //
    // "favorite" : Icons.favorite,
    // "face" : Icons.face,
    // "facebook" : Icons.facebook,
    // "fact_check" : Icons.fact_check,
    // "family_restroom" : Icons.family_restroom,
    // "fast_forward" : Icons.fast_forward,
    // "fast_rewind" : Icons.fast_rewind,
    // "fastfood" : Icons.fastfood,
    // "featured_video" : Icons.featured_video,
    // "feed" : Icons.feed,
    // "feedback" : Icons.feedback,
    // "female" : Icons.female,
    // "fence" : Icons.fence,
    // "festival" : Icons.festival,
    // "fiber_dvr" : Icons.fiber_dvr,
    // "fiber_new" : Icons.fiber_new,
    // "fiber_pin" : Icons.fiber_pin,
    // "fiber_manual_record" : Icons.fiber_manual_record,
    // "fiber_smart_record" : Icons.fiber_smart_record,
    // "fifteen_mp" : Icons.fifteen_mp,
    // "file_copy" : Icons.file_copy,
    // "file_present" : Icons.file_present,
    // "file_upload" : Icons.file_upload,
    // "filter" : Icons.filter,
    // "filter_alt" : Icons.filter_alt,
    // "filter_hdr" : Icons.filter_hdr,
    // "filter_list" : Icons.filter_list,
    // "filter_none" : Icons.filter_none,
    // "filter_vintage" : Icons.filter_vintage,
    // "find_in_page" : Icons.find_in_page,
    // "find_replace" : Icons.find_replace,
    // "fingerprint" : Icons.fingerprint,
    // "fire_extinguisher" : Icons.fire_extinguisher,
    // "fireplace" : Icons.fireplace,
    // "fit_screen" : Icons.fit_screen,
    // "fitness_center" : Icons.fitness_center,
    // "five_g" : Icons.five_g,
    // "five_k" : Icons.five_k,
    // "five_mp" : Icons.five_mp,
    // "flag" : Icons.flag,
    // "flaky" : Icons.flaky,
    // "flare" : Icons.flare,
    // "flash_auto" : Icons.flash_auto,
    // "flash_off" : Icons.flash_off,
    // "flight" : Icons.flight,
    // "flight_land" : Icons.flight_land,
    // "flight_takeoff" : Icons.flight_takeoff,
    // "flip" : Icons.flip,
    // "flourescent" : Icons.flourescent,
    // "flutter_dash" : Icons.flutter_dash,
    // "fmd_bad" : Icons.fmd_bad,
    // "folder" : Icons.folder,
    // "folder_open" : Icons.folder_open,
    // "follow_the_signs" : Icons.follow_the_signs,
    // "food_bank" : Icons.food_bank,
    // "format_bold" : Icons.format_bold,
    // "format_clear" : Icons.format_clear,
    // "format_color_fill" : Icons.format_color_fill,
    // "format_color_reset" : Icons.format_color_reset,
    // "format_color_text" : Icons.format_color_text,
    // "format_italic" : Icons.format_italic,
    // "format_paint" : Icons.format_paint,
    // "format_quote" : Icons.format_quote,
    // "format_shapes" : Icons.format_shapes,
    // "format_size" : Icons.format_size,
    // "format_strikethrough" : Icons.format_strikethrough,
    // "format_underline" : Icons.format_underline,
    // "forum" : Icons.forum,
    //
    //
    //
    //
    //
    // "view_compact" : Icons.view_compact,
    // "view_day" : Icons.view_day,
    // "view_headline" : Icons.view_headline,
    // "view_in_ar" : Icons.view_in_ar,
    // "view_list" : Icons.view_list,
    // "view_module" : Icons.view_module,
    // "villa" : Icons.villa,
    // "visibility" : Icons.visibility,
    // "vignette" : Icons.vignette,
    // "visibility_off" : Icons.visibility_off,
    // "voice_chat" : Icons.voice_chat,
    // "voice_over_off" : Icons.voice_over_off,
    // "voicemail" : Icons.voicemail,
    // "volume_down" : Icons.volume_down,
    // "volume_up" : Icons.volume_up,
    // "volume_mute" : Icons.volume_mute,
    // "volume_off" : Icons.volume_off,
    // "volunteer_activism" : Icons.volunteer_activism,
    // "vpn_key" : Icons.vpn_key,
    // "vpn_lock" : Icons.vpn_lock,
    // "vrpano" : Icons.vrpano,
    // "wallet_giftcard" : Icons.wallet_giftcard,
    // "wallet_membership" : Icons.wallet_membership,
    // "wallet_travel" : Icons.wallet_travel,
    // "wallpaper" : Icons.wallpaper,
    // "warning" : Icons.warning,
    // "wash" : Icons.wash,
    // "watch" : Icons.watch,
    // "water" : Icons.water,
    // "water_damage" : Icons.water_damage,
    // "waterfall_chart" : Icons.waterfall_chart,
    // "waves" : Icons.waves,
    // "wb_auto" : Icons.wb_auto,
    // "wb_cloudy" : Icons.wb_cloudy,
    // "wb_incandescent" : Icons.wb_incandescent,
    // "wb_iridescent" : Icons.wb_iridescent,
    // "wb_shade" : Icons.wb_shade,
    // "wb_sunny" : Icons.wb_sunny,
    // "wb_twighlight" : Icons.wb_twighlight,
    // "wc" : Icons.wc,
    // "web" : Icons.web,
    // "web_asset" : Icons.web_asset,
    // "web_stories" : Icons.web_stories,
    // "weekend" : Icons.weekend,
    // "whatshot" : Icons.whatshot,
    // "wheelchair_pickup" : Icons.wheelchair_pickup,
    // "where_to_vote" : Icons.where_to_vote,
    // "widgets" : Icons.widgets,
    // "wifi" : Icons.wifi,
    // "wifi_calling" : Icons.wifi_calling,
    // "wifi_lock" : Icons.wifi_lock,
    // "wifi_off" : Icons.wifi_off,
    // "wifi_protected_setup" : Icons.wifi_protected_setup,
    // "wifi_tethering" : Icons.wifi_tethering,
    // "window" : Icons.window,
    // "wine_bar" : Icons.wine_bar,
    // "work" : Icons.work,
    // "work_off" : Icons.work_off,
    // "workspaces" : Icons.workspaces,
    // "wrap_text" : Icons.wrap_text,
    // "wrong_location" : Icons.wrong_location,
    // "yard" : Icons.yard,
    // "youtube_searched_for" : Icons.youtube_searched_for,
    // "zoom_in" : Icons.zoom_in,
    // "zoom_out" : Icons.zoom_out,
    // "zoom_out_map" : Icons.zoom_out_map
  };
}