import 'package:flutter/material.dart';

class IconsMap {
  Map<String, IconData> allIcons = {

    //a

    "list": Icons.list,
    "infinity": Icons.all_inclusive,
    "accessibility": Icons.accessibility,
    "favorite": Icons.favorite,
    "snow_flake": Icons.ac_unit,
    "alarm": Icons.access_alarm,
    "time": Icons.access_time,
    "handicap": Icons.accessible,
    "handicap_forward": Icons.accessible_forward_outlined,
    "account_balance": Icons.account_balance,
    "wallet": Icons.account_balance_wallet,
    "account_box": Icons.account_box,
    "account_circle": Icons.account_circle,
    "hierarchy": Icons.account_tree,
    "hierarchy_empty": Icons.account_tree_outlined,
    "ad_units": Icons.ad_units,
    "adb": Icons.adb,
    "add": Icons.add,
    "add_a_photo": Icons.add_a_photo,
    "add_alarm": Icons.add_alarm,
    "add_alert": Icons.add_alert,
    "add_box": Icons.add_box,
    "add_business": Icons.add_business,
    "add_call": Icons.add_call,
    "add_chart": Icons.add_chart,
    "add_circle": Icons.add_circle,
    "add_comment": Icons.add_comment,
    "add_link": Icons.add_link,
    "add_location": Icons.add_location_alt_outlined,
    "add add_moderator": Icons.add_moderator,
    "add_image": Icons.add_photo_alternate_outlined,
    "add_reaction": Icons.add_reaction,
    "add_road": Icons.add_road,
    "add_shopping_cart": Icons.add_shopping_cart,
    "add_task": Icons.add_task,
    "add_to_drive": Icons.add_to_drive,
    "add_to_home_screen": Icons.add_to_home_screen,
    "add_to_photos_outlined": Icons.add_to_photos_outlined,
    "add_to_queue": Icons.add_to_queue,
    "addchart": Icons.addchart,
    "adjust" : Icons.adjust,
    "admin_panel_settings" : Icons.admin_panel_settings,
    "agriculture" : Icons.agriculture,
    "air" : Icons.air,
    "airline_seat_flat" : Icons.airline_seat_flat,
    "airline_seat_flat_angled" : Icons.airline_seat_flat_angled,
    "airline_seat_individual_suite" : Icons.airline_seat_individual_suite,
    "airline_seat_legroom_extra" : Icons.airline_seat_legroom_extra,
    "airline_seat_legroom_normal" : Icons.airline_seat_legroom_normal,
    "airline_seat_legroom_reduced" : Icons.airline_seat_legroom_reduced,
    "airline_seat_recline_extra" : Icons.airline_seat_recline_extra,
    "airline_seat_recline_normal" : Icons.airline_seat_recline_normal,
    "airplane_ticket" : Icons.airplane_ticket,
    "airplanemode_active" : Icons.airplanemode_active,
    "airplanemode_inactive" : Icons.airplanemode_inactive,
    "airplay" : Icons.airplay,
    "airport_shuttle" : Icons.airport_shuttle,
    "alarm_off" : Icons.alarm_off,
    "alarm_on" : Icons.alarm_on,
    "album" : Icons.album,
    "align_horizontal_center" : Icons.align_horizontal_center,
    "align_horizontal_left" : Icons.align_horizontal_left,
    "align_horizontal_right" : Icons.align_horizontal_right,
    "align_vertical_center" : Icons.align_vertical_center,
    "align_vertical_bottom" : Icons.align_vertical_bottom,
    "align_vertical_top" : Icons.align_vertical_top,
    "all_inbox" : Icons.all_inbox,
    "all_out" : Icons.all_out,
    "alt_route" : Icons.alt_route,
    "alternate_email" : Icons.alternate_email,
    "amp_stories" : Icons.amp_stories,
    "analytics" : Icons.analytics,
    "anchor" : Icons.anchor,
    "android" : Icons.android,
    "animation" : Icons.animation,
    "announcement" : Icons.announcement,
    "aod" : Icons.aod,
    "apartment" : Icons.apartment,
    "api" : Icons.api,
    "app_blocking" : Icons.app_blocking,
    "app_registration" : Icons.app_registration,
    "app_settings_alt" : Icons.app_settings_alt,
    "approval" : Icons.approval,
    "apps" : Icons.apps,
    "architecture" : Icons.architecture,
    "archive" : Icons.archive,
    "arrow_back" : Icons.arrow_back,
    "arrow_circle_down" : Icons.arrow_circle_down,
    "arrow_circle_up" : Icons.arrow_circle_up,
    "arrow_downward" : Icons.arrow_downward,
    "arrow_drop_down" : Icons.arrow_drop_down,
    "arrow_drop_up" : Icons.arrow_drop_up,
    "arrow_forward" : Icons.arrow_forward,
    "arrow_left" : Icons.arrow_left,
    "arrow_upward" : Icons.arrow_upward,
    "arrow_right" : Icons.arrow_right,
    "art_track" : Icons.art_track,
    "article" : Icons.article,
    "aspect_ratio" : Icons.aspect_ratio,
    "assessment" : Icons.assessment,
    "assignment" : Icons.assignment,
    "assignment_late" : Icons.assignment_late,
    "assignment_return" : Icons.assignment_return,
    "assignment_returned" : Icons.assignment_returned,
    "assignment_turned_in" : Icons.assignment_turned_in,
    "assistant" : Icons.assistant,
    "assistant_direction" : Icons.assistant_direction,
    "assistant_navigation" : Icons.assistant_navigation,
    "assistant_photo" : Icons.assistant_photo,
    "atm" : Icons.atm,
    "attach_email" : Icons.attach_email,
    "attach_file" : Icons.attach_file,
    "attach_money" : Icons.attach_money,

    //b
    "baby_changing_station" : Icons.baby_changing_station,
    "" : Icons.backpack,
    "backpack" : Icons.backspace,
    "backup" : Icons.backup,
    "badge" : Icons.badge,
    "bakery_dining" : Icons.bakery_dining,
    "balcony" : Icons.balcony,
    "ballot" : Icons.ballot,
    "bar_chart" : Icons.bar_chart,
    "batch_prediction" : Icons.batch_prediction,
    "bathroom" : Icons.bathroom,
    "bathtub" : Icons.bathtub,
    "battery_alert" : Icons.battery_alert,
    "battery_charging_full" : Icons.battery_charging_full,
    "battery_full" : Icons.battery_full,
    "battery_unknown" : Icons.battery_unknown,
    "beach_access" : Icons.beach_access,
    "bed" : Icons.bed,
    "bedroom_baby" : Icons.bedroom_baby,
    "bedroom_child" : Icons.bedroom_child,
    "bedroom_parent" : Icons.bedroom_parent,
    "bedtime" : Icons.bedtime,
    "beenhere" : Icons.beenhere,
    "bento" : Icons.bento,
    "bike_scooter" : Icons.bike_scooter,
    "biotech" : Icons.biotech,
    "blender" : Icons.blender,
    "block" : Icons.block,
    "bloodtype" : Icons.bloodtype,
    "bluetooth" : Icons.bluetooth,
    "bluetooth_connected" : Icons.bluetooth_connected,
    "bluetooth_disabled" : Icons.bluetooth_disabled,
    "blur_circular" : Icons.blur_circular,
    "blur_linear" : Icons.blur_linear,
    "blur_off" : Icons.blur_off,
    "blur_on" : Icons.blur_on,
    "bolt" : Icons.bolt,
    "book" : Icons.book,
    "book_online" : Icons.book_online,
    "bookmark" : Icons.bookmark,
    "bookmark_remove" : Icons.bookmark_remove,
    "border_color" : Icons.border_color,
    "border_all" : Icons.border_all,
    "border_clear" : Icons.border_clear,
    "branding_watermark" : Icons.branding_watermark,
    "breakfast_dining" : Icons.breakfast_dining,
    "brunch_dining" : Icons.brunch_dining,
    "brush" : Icons.brush,
    "bubble_chart" : Icons.bubble_chart,
    "bug_report" : Icons.bug_report,
    "build" : Icons.build,
    "bungalow" : Icons.bungalow,
    "burst_mode" : Icons.burst_mode,
    "bus_alert" : Icons.bus_alert,
    "business" : Icons.business,


    //c
    "calendar_view_week" : Icons.calendar_view_week,
    "calendar_view_month" : Icons.calendar_view_month,
    "calendar_view_day" : Icons.calendar_view_day,
    "clear" : Icons.clear,
    "cabin" : Icons.cabin,
    "cached" : Icons.cached,
    "cake" : Icons.cake,
    "calculate" : Icons.calculate,
    "calendar_today" : Icons.calendar_today,
    "call" : Icons.call,
    "call_end" : Icons.call_end,
    "call_made" : Icons.call_made,
    "call_merge" : Icons.call_merge,
    "call_missed" : Icons.call_missed,
    "call_received" : Icons.call_received,
    "camera" : Icons.camera,
    "camera_front" : Icons.camera_front,
    "camera_rear" : Icons.camera_rear,
    "camera_roll" : Icons.camera_roll,
    "campaign" : Icons.campaign,
    "cancel" : Icons.cancel,
    "cancel_schedule_send" : Icons.cancel_schedule_send,
    "car_rental" : Icons.car_rental,
    "car_repair" : Icons.car_repair,
    "card_membership" : Icons.card_membership,
    "carpenter" : Icons.carpenter,
    "cases" : Icons.cases,
    "casino" : Icons.casino,
    "cast" : Icons.cast,
    "category" : Icons.category,
    "compare_arrows" : Icons.compare_arrows,
    "celebration" : Icons.celebration,
    "chair" : Icons.chair,
    "chalet" : Icons.chalet,
    "change_history" : Icons.change_history,
    "charging_station" : Icons.charging_station,
    "checklist" : Icons.checklist,
    "checkroom" : Icons.checkroom,
    "child_care" : Icons.child_care,
    "child_friendly" : Icons.child_friendly,
    "clean_hands" : Icons.clean_hands,
    "circle" : Icons.circle,
    "cleaning_services" : Icons.cleaning_services,
    "close" : Icons.close,
    "close_fullscreen" : Icons.close_fullscreen,
    "closed_caption" : Icons.closed_caption,
    "closed_caption_disabled" : Icons.closed_caption_disabled,
    "closed_caption_off" : Icons.closed_caption_off,
    "cloud" : Icons.cloud,
    "cloud_done" : Icons.cloud_done,
    "cloud_download" : Icons.cloud_download,
    "cloud_off" : Icons.cloud_off,
    "code" : Icons.code,
    "coffee" : Icons.coffee,
    "coffee_maker" : Icons.coffee_maker,
    "collections" : Icons.collections,
    "color_lens" : Icons.color_lens,
    "colorize" : Icons.colorize,
    "comment" : Icons.comment,
    "commute" : Icons.commute,
    "compass_calibration" : Icons.compass_calibration,
    "compress" : Icons.compress,
    "computer" : Icons.computer,
    "connect_without_contact" : Icons.connect_without_contact,
    "connected_tv" : Icons.connected_tv,
    "construction" : Icons.construction,
    "contact_mail" : Icons.contact_mail,
    "contact_support" : Icons.contact_support,
    "contactless" : Icons.contactless,
    "contacts" : Icons.contacts,
    "content_copy" : Icons.content_copy,
    "content_cut" : Icons.content_cut,
    "content_paste" : Icons.content_paste,



    "view_compact" : Icons.view_compact,
    "view_day" : Icons.view_day,
    "view_headline" : Icons.view_headline,
    "view_in_ar" : Icons.view_in_ar,
    "view_list" : Icons.view_list,
    "view_module" : Icons.view_module,
    "calendar_view_day" : Icons.calendar_view_day,
    "calendar_view_month" : Icons.calendar_view_month,
    "calendar_view_week" : Icons.calendar_view_week,
    "villa" : Icons.villa,
    "visibility" : Icons.visibility,
    "vignette" : Icons.vignette,
    "visibility_off" : Icons.visibility_off,
    "voice_chat" : Icons.voice_chat,
    "voice_over_off" : Icons.voice_over_off,
    "voicemail" : Icons.voicemail,
    "volume_down" : Icons.volume_down,
    "volume_up" : Icons.volume_up,
    "volume_mute" : Icons.volume_mute,
    "volume_off" : Icons.volume_off,
    "volunteer_activism" : Icons.volunteer_activism,
    "vpn_key" : Icons.vpn_key,
    "vpn_lock" : Icons.vpn_lock,
    "vrpano" : Icons.vrpano,
    "wallet_giftcard" : Icons.wallet_giftcard,
    "wallet_membership" : Icons.wallet_membership,
    "wallet_travel" : Icons.wallet_travel,
    "wallpaper" : Icons.wallpaper,
    "warning" : Icons.warning,
    "wash" : Icons.wash,
    "watch" : Icons.watch,
    "water" : Icons.water,
    "water_damage" : Icons.water_damage,
    "waterfall_chart" : Icons.waterfall_chart,
    "waves" : Icons.waves,
    "wb_auto" : Icons.wb_auto,
    "wb_cloudy" : Icons.wb_cloudy,
    "wb_incandescent" : Icons.wb_incandescent,
    "wb_iridescent" : Icons.wb_iridescent,
    "wb_shade" : Icons.wb_shade,
    "wb_sunny" : Icons.wb_sunny,
    "wb_twighlight" : Icons.wb_twighlight,
    "wc" : Icons.wc,
    "web" : Icons.web,
    "web_asset" : Icons.web_asset,
    "web_stories" : Icons.web_stories,
    "weekend" : Icons.weekend,
    "whatshot" : Icons.whatshot,
    "wheelchair_pickup" : Icons.wheelchair_pickup,
    "where_to_vote" : Icons.where_to_vote,
    "widgets" : Icons.widgets,
    "wifi" : Icons.wifi,
    "wifi_calling" : Icons.wifi_calling,
    "wifi_lock" : Icons.wifi_lock,
    "wifi_off" : Icons.wifi_off,
    "wifi_protected_setup" : Icons.wifi_protected_setup,
    "wifi_tethering" : Icons.wifi_tethering,
    "window" : Icons.window,
    "wine_bar" : Icons.wine_bar,
    "work" : Icons.work,
    "work_off" : Icons.work_off,
    "workspaces" : Icons.workspaces,
    "wrap_text" : Icons.wrap_text,
    "wrong_location" : Icons.wrong_location,
    "yard" : Icons.yard,
    "youtube_searched_for" : Icons.youtube_searched_for,
    "zoom_in" : Icons.zoom_in,
    "zoom_out" : Icons.zoom_out,
    "zoom_out_map" : Icons.zoom_out_map
  };
}