import 'package:flutter/material.dart';

import 'TranslationService.dart';

class IconsMap {
  Map<Translation, IconData> allIcons = {

    //a

    Translation("list"): Icons.list,
    Translation("infinity"): Icons.all_inclusive,
    Translation("accessibility"): Icons.accessibility,
    Translation("snow_flake"): Icons.ac_unit,
    Translation("alarm"): Icons.access_alarm,
    Translation("time"): Icons.access_time,
    Translation("handicap"): Icons.accessible,
    Translation("handicap_forward"): Icons.accessible_forward_outlined,
    Translation("account_balance"): Icons.account_balance,
    Translation("wallet"): Icons.account_balance_wallet,
    Translation("account_box"): Icons.account_box,
    Translation("account_circle"): Icons.account_circle,
    Translation("hierarchy"): Icons.account_tree,
    Translation("hierarchy_empty"): Icons.account_tree_outlined,
    Translation("ad_units"): Icons.ad_units,
    Translation("adb"): Icons.adb,
    Translation("add"): Icons.add,
    Translation("add_a_photo"): Icons.add_a_photo,
    Translation("add_alarm"): Icons.add_alarm,
    Translation("add_alert"): Icons.add_alert,
    Translation("add_box"): Icons.add_box,
    Translation("add_business"): Icons.add_business,
    Translation("add_call"): Icons.add_call,
    Translation("add_chart"): Icons.add_chart,
    Translation("add_circle"): Icons.add_circle,
    Translation("add_comment"): Icons.add_comment,
    Translation("add_link"): Icons.add_link,
    Translation("add_location"): Icons.add_location_alt_outlined,
    Translation("add_add_moderator"): Icons.add_moderator,
    Translation("add_image"): Icons.add_photo_alternate_outlined,
    Translation("add_reaction"): Icons.add_reaction,
    Translation("add_road"): Icons.add_road,
    Translation("add_shopping_cart"): Icons.add_shopping_cart,
    Translation("add_task"): Icons.add_task,
    Translation("add_to_drive"): Icons.add_to_drive,
    Translation("add_to_home_screen"): Icons.add_to_home_screen,
    Translation("add_to_photos_outlined"): Icons.add_to_photos_outlined,
    Translation("add_to_queue"): Icons.add_to_queue,
    Translation("adjust") : Icons.adjust,
    Translation("admin_panel_settings") : Icons.admin_panel_settings,
    Translation("agriculture") : Icons.agriculture,
    Translation("air") : Icons.air,
    Translation("airline_seat_flat") : Icons.airline_seat_flat,
    Translation("airline_seat_flat_angled") : Icons.airline_seat_flat_angled,
    Translation("airline_seat_individual_suite") : Icons.airline_seat_individual_suite,
    Translation("airline_seat_legroom_extra") : Icons.airline_seat_legroom_extra,
    Translation("airline_seat_legroom_normal") : Icons.airline_seat_legroom_normal,
    Translation("airline_seat_legroom_reduced") : Icons.airline_seat_legroom_reduced,
    Translation("airline_seat_recline_extra") : Icons.airline_seat_recline_extra,
    Translation("airline_seat_recline_normal") : Icons.airline_seat_recline_normal,
    Translation("airplane_ticket") : Icons.airplane_ticket,
    Translation("airplanemode_active") : Icons.airplanemode_active,
    Translation("airplanemode_inactive") : Icons.airplanemode_inactive,
    Translation("airplay") : Icons.airplay,
    Translation("airport_shuttle") : Icons.airport_shuttle,
    Translation("alarm_off") : Icons.alarm_off,
    Translation("alarm_on") : Icons.alarm_on,
    Translation("album") : Icons.album,
    Translation("align_horizontal_center") : Icons.align_horizontal_center,
    Translation("align_horizontal_left") : Icons.align_horizontal_left,
    Translation("align_horizontal_right") : Icons.align_horizontal_right,
    Translation("align_vertical_center") : Icons.align_vertical_center,
    Translation("align_vertical_bottom") : Icons.align_vertical_bottom,
    Translation("align_vertical_top") : Icons.align_vertical_top,
    Translation("all_inbox") : Icons.all_inbox,
    Translation("all_out") : Icons.all_out,
    Translation("alt_route") : Icons.alt_route,
    Translation("alternate_email") : Icons.alternate_email,
    Translation("amp_stories") : Icons.amp_stories,
    Translation("analytics") : Icons.analytics,
    Translation("anchor") : Icons.anchor,
    Translation("android") : Icons.android,
    Translation("animation") : Icons.animation,
    Translation("announcement") : Icons.announcement,
    Translation("aod") : Icons.aod,
    Translation("apartment") : Icons.apartment,
    Translation("api") : Icons.api,
    Translation("app_blocking"): Icons.app_blocking,
    Translation("app_registration") : Icons.app_registration,
    Translation("app_settings_alt") : Icons.app_settings_alt,
    Translation("approval") : Icons.approval,
    Translation("apps") : Icons.apps,
    Translation("architecture") : Icons.architecture,
    Translation("archive") : Icons.archive,
    Translation("arrow_back") : Icons.arrow_back,
    Translation("arrow_downward") : Icons.arrow_downward,
    Translation("arrow_forward") : Icons.arrow_forward,
    Translation("arrow_upward") : Icons.arrow_upward,
    Translation("article") : Icons.article,
    Translation("aspect_ratio") : Icons.aspect_ratio,
    Translation("assessment") : Icons.assessment,
    Translation("assignment") : Icons.assignment,
    Translation("assignment_late") : Icons.assignment_late,
    Translation("assignment_return") : Icons.assignment_return,
    Translation("assignment_returned") : Icons.assignment_returned,
    Translation("assignment_turned_in") : Icons.assignment_turned_in,
    Translation("assistant") : Icons.assistant,
    Translation("assistant_direction") : Icons.assistant_direction,
    Translation("assistant_navigation") : Icons.assistant_navigation,
    Translation("assistant_photo") : Icons.assistant_photo,
    Translation("atm") : Icons.atm,
    Translation("attach_email") : Icons.attach_email,
    Translation("attach_file") : Icons.attach_file,
    Translation("attach_money") : Icons.attach_money,

    //b
    Translation("baby_changing_station") : Icons.baby_changing_station,
    Translation("backpack2") : Icons.backpack,
    Translation("backspace") : Icons.backspace,
    Translation("backup") : Icons.backup,
    Translation("badge") : Icons.badge,
    Translation("bakery_dining") : Icons.bakery_dining,
    Translation("balcony") : Icons.balcony,
    Translation("ballot") : Icons.ballot,
    Translation("bar_chart") : Icons.bar_chart,
    Translation("batch_prediction") : Icons.batch_prediction,
    Translation("bathroom") : Icons.bathroom,
    Translation("bathtub") : Icons.bathtub,
    Translation("battery_alert") : Icons.battery_alert,
    Translation("battery_charging_full") : Icons.battery_charging_full,
    Translation("battery_full") : Icons.battery_full,
    Translation("battery_unknown") : Icons.battery_unknown,
    Translation("beach_access") : Icons.beach_access,
    Translation("bed") : Icons.bed,
    Translation("bedroom_baby") : Icons.bedroom_baby,
    Translation("bedroom_child") : Icons.bedroom_child,
    Translation("bedroom_parent") : Icons.bedroom_parent,
    Translation("bedtime") : Icons.bedtime,
    Translation("beenhere") : Icons.beenhere,
    Translation("bento") : Icons.bento,
    Translation("bike_scooter") : Icons.bike_scooter,
    Translation("biotech") : Icons.biotech,
    Translation("blender") : Icons.blender,
    Translation("block") : Icons.block,
    Translation("bloodtype") : Icons.bloodtype,
    Translation("bluetooth") : Icons.bluetooth,
    Translation("bluetooth_connected") : Icons.bluetooth_connected,
    Translation("bluetooth_disabled") : Icons.bluetooth_disabled,
    Translation("blur_circular") : Icons.blur_circular,
    Translation("blur_linear") : Icons.blur_linear,
    Translation("blur_off") : Icons.blur_off,
    Translation("blur_on") : Icons.blur_on,
    Translation("bolt") : Icons.bolt,
    Translation("book") : Icons.book,
    Translation("bookmark") : Icons.bookmark,
    Translation("bookmark_remove") : Icons.bookmark_remove,
    Translation("border_color") : Icons.border_color,
    Translation("border_all") : Icons.border_all,
    Translation("border_clear") : Icons.border_clear,
    Translation("branding_watermark") : Icons.branding_watermark,
    Translation("breakfast_dining") : Icons.breakfast_dining,
    Translation("brunch_dining") : Icons.brunch_dining,
    Translation("brush") : Icons.brush,
    Translation("bubble_chart") : Icons.bubble_chart,
    Translation("bug_report") : Icons.bug_report,
    Translation("build") : Icons.build,
    Translation("bungalow") : Icons.bungalow,
    Translation("burst_mode") : Icons.burst_mode,
    Translation("bus_alert") : Icons.bus_alert,
    Translation("business") : Icons.business,

    //
    // //c
    Translation("calendar_view_week") : Icons.calendar_view_week,
    Translation("calendar_view_month") : Icons.calendar_view_month,
    Translation("calendar_view_day") : Icons.calendar_view_day,
    Translation("clear") : Icons.clear,
    Translation("cabin") : Icons.cabin,
    Translation("cached") : Icons.cached,
    Translation("cake") : Icons.cake,
    Translation("calculate") : Icons.calculate,
    Translation("calendar_today") : Icons.calendar_today,
    Translation("call") : Icons.call,
    Translation("call_end") : Icons.call_end,
    Translation("call_made") : Icons.call_made,
    Translation("call_merge") : Icons.call_merge,
    Translation("call_missed") : Icons.call_missed,
    Translation("call_received") : Icons.call_received,
    Translation("camera") : Icons.camera,
    Translation("camera_front") : Icons.camera_front,
    Translation("camera_rear") : Icons.camera_rear,
    Translation("camera_roll") : Icons.camera_roll,
    Translation("campaign") : Icons.campaign,
    Translation("cancel") : Icons.cancel,
    Translation("car_rental") : Icons.car_rental,
    Translation("car_repair") : Icons.car_repair,
    Translation("card_membership") : Icons.card_membership,
    Translation("carpenter") : Icons.carpenter,
    Translation("cases") : Icons.cases,
    Translation("casino") : Icons.casino,
    Translation("cast") : Icons.cast,
    Translation("category") : Icons.category,
    Translation("compare_arrows") : Icons.compare_arrows,
    Translation("celebration") : Icons.celebration,
    Translation("chair") : Icons.chair,
    Translation("chalet") : Icons.chalet,
    Translation("charging_station") : Icons.charging_station,
    Translation("checklist") : Icons.checklist,
    Translation("checkroom") : Icons.checkroom,
    Translation("child_care") : Icons.child_care,
    Translation("child_friendly") : Icons.child_friendly,
    Translation("clean_hands") : Icons.clean_hands,
    Translation("circle") : Icons.circle,
    Translation("cleaning_services") : Icons.cleaning_services,
    Translation("close_fullscreen") : Icons.close_fullscreen,
    Translation("closed_caption") : Icons.closed_caption,
    Translation("closed_caption_disabled") : Icons.closed_caption_disabled,
    Translation("closed_caption_off") : Icons.closed_caption_off,
    Translation("cloud") : Icons.cloud,
    Translation("cloud_done") : Icons.cloud_done,
    Translation("cloud_download") : Icons.cloud_download,
    Translation("cloud_off") : Icons.cloud_off,
    Translation("code") : Icons.code,
    Translation("coffee") : Icons.coffee,
    Translation("coffee_maker") : Icons.coffee_maker,
    Translation("collections") : Icons.collections,
    Translation("color_lens") : Icons.color_lens,
    Translation("colorize") : Icons.colorize,
    Translation("comment") : Icons.comment,
    Translation("commute") : Icons.commute,
    Translation("compress") : Icons.compress,
    Translation("computer") : Icons.computer,
    Translation("connect_without_contact") : Icons.connect_without_contact,
    Translation("connected_tv") : Icons.connected_tv,
    Translation("construction") : Icons.construction,
    Translation("contact_mail") : Icons.contact_mail,
    Translation("contact_support") : Icons.contact_support,
    Translation("contactless") : Icons.contactless,
    Translation("contacts") : Icons.contacts,
    Translation("content_copy") : Icons.content_copy,
    Translation("content_cut") : Icons.content_cut,
    Translation("content_paste") : Icons.content_paste,



    //d
    Translation("delete") : Icons.delete,
    Translation("dangerous") : Icons.dangerous,
    Translation("dark_mode") : Icons.dark_mode,
    Translation("dashboard") : Icons.dashboard,
    Translation("dashboard_customize") : Icons.dashboard_customize,
    Translation("data_saver_off") : Icons.data_saver_off,
    Translation("data_saver_on") : Icons.data_saver_on,
    Translation("data_usage") : Icons.data_usage,
    Translation("date_range") : Icons.date_range,
    Translation("deck") : Icons.deck,
    Translation("dehaze") : Icons.dehaze,
    Translation("delivery_dining") : Icons.delivery_dining,
    Translation("departure_board") : Icons.departure_board,
    Translation("description") : Icons.description,
    Translation("design_services") : Icons.design_services,
    Translation("desktop_access_disabled") : Icons.desktop_access_disabled,
    Translation("desktop_mac") : Icons.desktop_mac,
    Translation("details") : Icons.details,
    Translation("developer_board") : Icons.developer_board,
    Translation("developer_board_off") : Icons.developer_board_off,
    Translation("developer_mode") : Icons.developer_mode,
    Translation("device_hub") : Icons.device_hub,
    Translation("device_thermostat") : Icons.device_thermostat,
    Translation("device_unknown") : Icons.device_unknown,
    Translation("devices") : Icons.devices,
    Translation("dialer_sip") : Icons.dialer_sip,
    Translation("dialpad") : Icons.dialpad,
    Translation("dining") : Icons.dining,
    Translation("dinner_dining") : Icons.dinner_dining,
    Translation("directions") : Icons.directions,
    Translation("directions_bike") : Icons.directions_bike,
    Translation("directions_boat") : Icons.directions_boat,
    Translation("directions_bus") : Icons.directions_bus,
    Translation("directions_car") : Icons.directions_car,
    Translation("directions_ferry") : Icons.directions_ferry,
    Translation("directions_off") : Icons.directions_off,
    Translation("directions_run") : Icons.directions_run,
    Translation("directions_subway") : Icons.directions_subway,
    Translation("directions_train") : Icons.directions_train,
    Translation("directions_walk") : Icons.directions_walk,
    Translation("dirty_lens") : Icons.dirty_lens,
    Translation("disabled_by_default") : Icons.disabled_by_default,
    Translation("disc_full") : Icons.disc_full,
    Translation("dns") : Icons.dns,
    Translation("do_disturb") : Icons.do_disturb,
    Translation("do_disturb_off") : Icons.do_disturb_off,
    Translation("do_not_step") : Icons.do_not_step,
    Translation("do_not_touch") : Icons.do_not_touch,
    Translation("dock") : Icons.dock,
    Translation("document_scanner") : Icons.document_scanner,
    Translation("domain") : Icons.domain,
    Translation("done") : Icons.done,
    Translation("done_all") : Icons.done_all,
    Translation("donut_large") : Icons.donut_large,
    Translation("door_back") : Icons.door_back,
    Translation("door_front") : Icons.door_front,
    Translation("door_sliding") : Icons.door_sliding,
    Translation("doorbell") : Icons.doorbell,
    Translation("downhill_skiing") : Icons.downhill_skiing,
    Translation("download") : Icons.download,
    Translation("download_done") : Icons.download_done,
    Translation("downloading") : Icons.downloading,
    Translation("drafts") : Icons.drafts,
    Translation("drive_file_move") : Icons.drive_file_move,
    Translation("dry") : Icons.dry,
    Translation("dry_cleaning") : Icons.dry_cleaning,
    Translation("duo") : Icons.duo,
    Translation("dvr") : Icons.dvr,



    //e

    Translation("e_mobiledata") : Icons.e_mobiledata,
    Translation("earbuds") : Icons.earbuds,
    Translation("eco") : Icons.eco,
    Translation("edgesensor_high") : Icons.edgesensor_high,
    Translation("edgesensor_low") : Icons.edgesensor_low,
    Translation("edit") : Icons.edit,
    Translation("edit_location") : Icons.edit_location,
    Translation("edit_off") : Icons.edit_off,
    Translation("edit_road") : Icons.edit_road,
    Translation("eject") : Icons.eject,
    Translation("elderly") : Icons.elderly,
    Translation("electric_bike") : Icons.electric_bike,
    Translation("electric_car") : Icons.electric_car,
    Translation("electric_moped") : Icons.electric_moped,
    Translation("electric_rickshaw") : Icons.electric_rickshaw,
    Translation("electric_scooter") : Icons.electric_scooter,
    Translation("electrical_services") : Icons.electrical_services,
    Translation("elevator") : Icons.elevator,
    Translation("email") : Icons.email,
    Translation("emoji_emotions") : Icons.emoji_emotions,
    Translation("emoji_events") : Icons.emoji_events,
    Translation("emoji_food_beverage") : Icons.emoji_food_beverage,
    Translation("emoji_nature") : Icons.emoji_nature,
    Translation("emoji_objects") : Icons.emoji_objects,
    Translation("emoji_people") : Icons.emoji_people,
    Translation("emoji_symbols") : Icons.emoji_symbols,
    Translation("emoji_transportation") : Icons.emoji_transportation,
    Translation("engineering") : Icons.engineering,
    Translation("equalizer") : Icons.equalizer,
    Translation("error") : Icons.error,
    Translation("escalator") : Icons.escalator,
    Translation("escalator_warning") : Icons.escalator_warning,
    Translation("euro") : Icons.euro,
    Translation("ev_station") : Icons.ev_station,
    Translation("event_available") : Icons.event_available,
    Translation("event_busy") : Icons.event_busy,
    Translation("event_seat") : Icons.event_seat,
    Translation("exit_to_app") : Icons.exit_to_app,
    Translation("expand") : Icons.expand,
    Translation("explicit") : Icons.explicit,
    Translation("explore") : Icons.explore,
    Translation("explore_off") : Icons.explore_off,
    Translation("exposure") : Icons.exposure,
    Translation("extension") : Icons.extension,


    // f

    Translation("favorite") : Icons.favorite,
    Translation("face") : Icons.face,
    Translation("facebook") : Icons.facebook,
    Translation("family_restroom") : Icons.family_restroom,
    Translation("fast_forward") : Icons.fast_forward,
    Translation("fast_rewind") : Icons.fast_rewind,
    Translation("fastfood") : Icons.fastfood,
    Translation("feed") : Icons.feed,
    Translation("feedback") : Icons.feedback,
    Translation("female") : Icons.female,
    Translation("fence") : Icons.fence,
    Translation("festival") : Icons.festival,
    Translation("fiber_dvr") : Icons.fiber_dvr,
    Translation("fiber_new") : Icons.fiber_new,
    Translation("fiber_pin") : Icons.fiber_pin,
    Translation("fiber_manual_record") : Icons.fiber_manual_record,
    Translation("fiber_smart_record") : Icons.fiber_smart_record,
    Translation("filter") : Icons.filter,
    Translation("filter_alt") : Icons.filter_alt,
    Translation("filter_hdr") : Icons.filter_hdr,
    Translation("filter_list") : Icons.filter_list,
    Translation("filter_none") : Icons.filter_none,
    Translation("filter_vintage") : Icons.filter_vintage,
    Translation("find_in_page") : Icons.find_in_page,
    Translation("find_replace") : Icons.find_replace,
    Translation("fingerprint") : Icons.fingerprint,
    Translation("fire_extinguisher") : Icons.fire_extinguisher,
    Translation("fireplace") : Icons.fireplace,
    Translation("fit_screen") : Icons.fit_screen,
    Translation("fitness_center") : Icons.fitness_center,
    Translation("five_g") : Icons.five_g,
    Translation("five_k") : Icons.five_k,
    Translation("flag") : Icons.flag,
    Translation("flaky") : Icons.flaky,
    Translation("flare") : Icons.flare,
    Translation("flash_auto") : Icons.flash_auto,
    Translation("flash_off") : Icons.flash_off,
    Translation("flight") : Icons.flight,
    Translation("flight_land") : Icons.flight_land,
    Translation("flight_takeoff") : Icons.flight_takeoff,
    Translation("flip") : Icons.flip,
    Translation("flourescent") : Icons.flourescent,
    Translation("folder") : Icons.folder,
    Translation("follow_the_signs") : Icons.follow_the_signs,
    Translation("food_bank") : Icons.food_bank,
    Translation("format_bold") : Icons.format_bold,
    Translation("format_clear") : Icons.format_clear,
    Translation("format_color_fill") : Icons.format_color_fill,
    Translation("format_color_reset") : Icons.format_color_reset,
    Translation("format_color_text") : Icons.format_color_text,
    Translation("format_italic") : Icons.format_italic,
    Translation("format_paint") : Icons.format_paint,
    Translation("format_quote") : Icons.format_quote,
    Translation("format_shapes") : Icons.format_shapes,
    Translation("format_size") : Icons.format_size,
    Translation("format_strikethrough") : Icons.format_strikethrough,
    Translation("format_underline") : Icons.format_underline,
    Translation("forum") : Icons.forum,



    //
    //
    // "view_compact" : Icons.view_compact,
    // "view_day" : Icons.view_day,
    // "view_headline" : Icons.view_headline,
    // "view_in_ar" : Icons.view_in_ar,
    // "view_list" : Icons.view_list,
    // "view_module" : Icons.view_module,
    // "villa" : Icons.villa,
    // "visibility" : Icons.visibility,
    // "vignette" : Icons.vignette,
    // "visibility_off" : Icons.visibility_off,
    // "voice_chat" : Icons.voice_chat,
    // "voice_over_off" : Icons.voice_over_off,
    // "voicemail" : Icons.voicemail,
    // "volume_down" : Icons.volume_down,
    // "volume_up" : Icons.volume_up,
    // "volume_mute" : Icons.volume_mute,
    // "volume_off" : Icons.volume_off,
    // "volunteer_activism" : Icons.volunteer_activism,
    // "vpn_key" : Icons.vpn_key,
    // "vpn_lock" : Icons.vpn_lock,
    // "vrpano" : Icons.vrpano,
    // "wallet_giftcard" : Icons.wallet_giftcard,
    // "wallet_membership" : Icons.wallet_membership,
    // "wallet_travel" : Icons.wallet_travel,
    // "wallpaper" : Icons.wallpaper,
    // "warning" : Icons.warning,
    // "wash" : Icons.wash,
    // "watch" : Icons.watch,
    // "water" : Icons.water,
    // "water_damage" : Icons.water_damage,
    // "waterfall_chart" : Icons.waterfall_chart,
    // "waves" : Icons.waves,
    // "wb_auto" : Icons.wb_auto,
    // "wb_cloudy" : Icons.wb_cloudy,
    // "wb_incandescent" : Icons.wb_incandescent,
    // "wb_iridescent" : Icons.wb_iridescent,
    // "wb_shade" : Icons.wb_shade,
    // "wb_sunny" : Icons.wb_sunny,
    // "wb_twighlight" : Icons.wb_twighlight,
    // "wc" : Icons.wc,
    // "web" : Icons.web,
    // "web_asset" : Icons.web_asset,
    // "web_stories" : Icons.web_stories,
    // "weekend" : Icons.weekend,
    // "whatshot" : Icons.whatshot,
    // "wheelchair_pickup" : Icons.wheelchair_pickup,
    // "where_to_vote" : Icons.where_to_vote,
    // "widgets" : Icons.widgets,
    // "wifi" : Icons.wifi,
    // "wifi_calling" : Icons.wifi_calling,
    // "wifi_lock" : Icons.wifi_lock,
    // "wifi_off" : Icons.wifi_off,
    // "wifi_protected_setup" : Icons.wifi_protected_setup,
    // "wifi_tethering" : Icons.wifi_tethering,
    // "window" : Icons.window,
    // "wine_bar" : Icons.wine_bar,
    // "work" : Icons.work,
    // "work_off" : Icons.work_off,
    // "workspaces" : Icons.workspaces,
    // "wrap_text" : Icons.wrap_text,
    // "wrong_location" : Icons.wrong_location,
    // "yard" : Icons.yard,
    // "youtube_searched_for" : Icons.youtube_searched_for,
    // "zoom_in" : Icons.zoom_in,
    // "zoom_out" : Icons.zoom_out,
    // "zoom_out_map" : Icons.zoom_out_map
  };
}